"""
Созданный с помощью QTDesigner графический интерфейс.
Импорт в файл питона командой из cmd: pyuic6 -x assistant.ui > assistapp.py
"""

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 716)
        MainWindow.setMinimumSize(QtCore.QSize(652, 612))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"")
        # sizes
        self.sidebarClosedSize = QtCore.QSize(0, 16777215)
        self.sidebarOpenedSize = QtCore.QSize(200, 1677215)
        self.frameMessagesSize = QtCore.QSize(16777215, 120)
        #
        MainWindow.setIconSize(QtCore.QSize(34, 34))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.sidebarClosedSize = QtCore.QSize(0, 16777215)
        self.sidebarOpenedSize = QtCore.QSize(200, 1677215)


        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        # изначально закрыто
        self.sidebar.setMaximumSize(self.sidebarClosedSize)

        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        self.sidebar.setFont(font)
        self.sidebar.setStyleSheet("background-color: rgb(0, 0, 84);")
        self.sidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titlemenu = QtWidgets.QFrame(self.sidebar)
        self.titlemenu.setMaximumSize(QtCore.QSize(16777215, 80))
        self.titlemenu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titlemenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.titlemenu.setObjectName("titlemenu")
        self.logotip = QtWidgets.QPushButton(self.titlemenu)
        self.logotip.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.logotip.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../KING/Новая папка (2)/images (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logotip.setIcon(icon)
        self.logotip.setIconSize(QtCore.QSize(70, 70))
        self.logotip.setObjectName("logotip")
        self.AppTitle = QtWidgets.QLabel(self.titlemenu)
        self.AppTitle.setGeometry(QtCore.QRect(80, 20, 101, 41))
        self.AppTitle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Terminal\";")
        self.AppTitle.setObjectName("AppTitle")
        self.verticalLayout_2.addWidget(self.titlemenu)
        self.frame_2 = QtWidgets.QFrame(self.sidebar)
        self.frame_2.setStyleSheet("font: 14pt \"Terminal\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.toolBox = QtWidgets.QToolBox(self.frame_2)
        self.toolBox.setGeometry(QtCore.QRect(10, 100, 181, 291))
        self.toolBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolBox.setObjectName("toolBox")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setGeometry(QtCore.QRect(0, 0, 181, 259))
        self.Settings.setObjectName("Settings")
        self.volume = QtWidgets.QSlider(self.Settings)
        self.volume.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.volume.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume.setObjectName("volume")
        self.speed = QtWidgets.QSlider(self.Settings)
        self.speed.setGeometry(QtCore.QRect(10, 180, 141, 21))
        self.speed.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.speed.setObjectName("speed")
        self.label = QtWidgets.QLabel(self.Settings)
        self.label.setGeometry(QtCore.QRect(60, 150, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Settings)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 71, 20))
        self.label_2.setObjectName("label_2")
        self.volume_2 = QtWidgets.QSlider(self.Settings)
        self.volume_2.setGeometry(QtCore.QRect(10, -40, 141, 21))
        self.volume_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_2.setObjectName("volume_2")
        self.toolBox.addItem(self.Settings, "")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.sidebar)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.exitbutton = QtWidgets.QPushButton(self.frame_4)
        self.exitbutton.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.exitbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Terminal\";")
        self.exitbutton.setObjectName("exitbutton")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.sidebar)
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        self.mainframe.setStyleSheet("\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.mainframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.mainframe)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sidebarOpen = QtWidgets.QPushButton(self.frame_3)
        self.sidebarOpen.setMaximumSize(QtCore.QSize(100, 200))
        self.sidebarOpen.setText("MENU")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../KING/4027495-200.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sidebarOpen.setIcon(icon1)
        self.sidebarOpen.setIconSize(QtCore.QSize(70, 70))
        self.sidebarOpen.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.sidebarOpen)
        self.titledialog = QtWidgets.QLabel(self.frame_3)
        self.titledialog.setStyleSheet("background-color: rgb(223, 223, 111);font: 14pt \"Terminal\";")
        self.titledialog.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titledialog.setObjectName("titledialog")
        self.horizontalLayout_2.addWidget(self.titledialog)
        self.verticalLayout.addWidget(self.frame_3)
        self.messages = QtWidgets.QFrame(self.mainframe)
        self.messages.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.messages.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.messages.setObjectName("messages")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.messages)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameMessages4 = QtWidgets.QFrame(self.messages)
        self.frameMessages4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMessages4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMessages4.setObjectName("frame")
        self.frameMessages4.setMaximumSize(self.frameMessagesSize)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameMessages4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fromwho4 = QtWidgets.QLabel(self.frameMessages4)
        self.fromwho4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.fromwho4.setStyleSheet("font: 14pt \"Terminal\";")
        self.fromwho4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fromwho4.setObjectName("fromwho4")
        self.horizontalLayout_3.addWidget(self.fromwho4)
        self.message4 = QtWidgets.QLabel(self.frameMessages4)
        self.message4.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 14pt \"Tahoma\";")
        self.message4.setObjectName("message4")
        self.horizontalLayout_3.addWidget(self.message4)
        self.verticalLayout_3.addWidget(self.frameMessages4)
        self.frameMessages3 = QtWidgets.QFrame(self.messages)
        self.frameMessages3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMessages3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMessages3.setObjectName("frame_5")
        self.frameMessages3.setMaximumSize(self.frameMessagesSize)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frameMessages3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fromwho3 = QtWidgets.QLabel(self.frameMessages3)
        self.fromwho3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.fromwho3.setStyleSheet("font: 14pt \"Terminal\";")
        self.fromwho3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fromwho3.setObjectName("fromwho3")
        self.horizontalLayout_4.addWidget(self.fromwho3)
        self.message3 = QtWidgets.QLabel(self.frameMessages3)
        self.message3.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 14pt \"Tahoma\";")
        self.message3.setObjectName("message3")
        self.horizontalLayout_4.addWidget(self.message3)
        self.verticalLayout_3.addWidget(self.frameMessages3)
        self.frameMessages2 = QtWidgets.QFrame(self.messages)
        self.frameMessages2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMessages2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMessages2.setObjectName("frame_6")
        self.frameMessages2.setMaximumSize(self.frameMessagesSize)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frameMessages2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fromwho2 = QtWidgets.QLabel(self.frameMessages2)
        self.fromwho2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.fromwho2.setStyleSheet("font: 14pt \"Terminal\";")
        self.fromwho2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fromwho2.setObjectName("fromwho2")
        self.horizontalLayout_6.addWidget(self.fromwho2)
        self.message2 = QtWidgets.QLabel(self.frameMessages2)
        self.message2.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 14pt \"Tahoma\";")
        self.message2.setObjectName("message2")
        self.horizontalLayout_6.addWidget(self.message2)
        self.verticalLayout_3.addWidget(self.frameMessages2)
        self.frameMessages1 = QtWidgets.QFrame(self.messages)
        self.frameMessages1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMessages1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMessages1.setObjectName("frame_7")
        self.frameMessages1.setMaximumSize(self.frameMessagesSize)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frameMessages1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fromwho1 = QtWidgets.QLabel(self.frameMessages1)
        self.fromwho1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.fromwho1.setStyleSheet("font: 14pt \"Terminal\";")
        self.fromwho1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fromwho1.setObjectName("fromwho1")
        self.horizontalLayout_5.addWidget(self.fromwho1)
        self.message1 = QtWidgets.QLabel(self.frameMessages1)
        self.message1.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 14pt \"Tahoma\";")
        self.message1.setObjectName("message1")
        self.horizontalLayout_5.addWidget(self.message1)
        self.verticalLayout_3.addWidget(self.frameMessages1)
        self.verticalLayout.addWidget(self.messages)
        self.buttonstart = QtWidgets.QFrame(self.mainframe)
        self.buttonstart.setMaximumSize(QtCore.QSize(16777215, 100))
        self.buttonstart.setStyleSheet("background-color: rgb(223, 223, 111);")
        self.buttonstart.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttonstart.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttonstart.setObjectName("buttonstart")
        self.startButton = QtWidgets.QPushButton(self.buttonstart)
        self.startButton.setGeometry(QtCore.QRect(250, 20, 301, 61))
        self.startButton.setStyleSheet("font: 14pt \"Terminal\";\n"
"\n"
"\n"
"")
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.buttonstart)
        self.horizontalLayout.addWidget(self.mainframe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.setMessageFrames()

    def setMessageFrames(self):
        """Убрать все рамки сообщений при запуске"""
        self.frameMessages1.hide()
        self.frameMessages2.hide()
        self.frameMessages3.hide()
        self.frameMessages4.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AppTitle.setText(_translate("MainWindow", "Assistant"))
        self.label.setText(_translate("MainWindow", "Speed"))
        self.label_2.setText(_translate("MainWindow", "Volume"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Settings), _translate("MainWindow", "Settings"))
        self.exitbutton.setText(_translate("MainWindow", "Exit"))
        self.titledialog.setText(_translate("MainWindow", "Dialog Window"))
        self.fromwho4.setText(_translate("MainWindow", "ME:"))
        self.message4.setText(_translate("MainWindow", "Привет"))
        self.fromwho3.setText(_translate("MainWindow", "ME:"))
        self.message3.setText(_translate("MainWindow", "Привет"))
        self.fromwho2.setText(_translate("MainWindow", "ME:"))
        self.message2.setText(_translate("MainWindow", "Привет"))
        self.fromwho1.setText(_translate("MainWindow", "ME:"))
        self.message1.setText(_translate("MainWindow", "Привет"))
        self.startButton.setText(_translate("MainWindow", "Start assistant"))
        self.action.setText(_translate("MainWindow", "Окно"))
        self.action_3.setText(_translate("MainWindow", "Конфигурация ассистента"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
